### ISSUE TITLE
ShardPool created shards failed when TickInterval set to 20ms on MacOS

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixcube#101]

**Comment by sukki37** [comment]
Only appeared on MacOS, part of error is as follows:
![image](https://user-images.githubusercontent.com/77312370/129441983-d3c857b8-5a44-4335-8ca7-c44bb369b78f.png)

**Comment by zhangxu19830126** [comment]
case1: ShardPool created shards failed when TickInterval set to 20ms on MacOS
