### ISSUE TITLE
Verifying module checksum mismatch

### ISSUE THREAD

**Issue by yingfeng** [matrixorigin/matrixcube#137]
Build error 
```
verifying github.com/pilosa/pilosa@v1.4.1: checksum mismatch
	downloaded: h1:BccOYZCzSpyL9JXv6M8W6n9KpAfRrCEAF9n/mFma0/E=
	go.sum:     h1:zSNyS/MqXTfRDNRBBNCApsOu2oUnTEj2uymCaqYSNx8=
```

If `go clean -modcache` is executed, then the build error disappears, however the same error would happen under building the main repo `matrixone`, and vice versa

**Comment by lignay** [comment]
Reproduced this issue in clean docker container build environment while running github action.
Please refer to https://github.com/matrixorigin/matrixcube/runs/3369272847?check_suite_focus=true 

Thanks,
Matthew
