### ISSUE TITLE
Multi-node cluster started failed

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixcube#186]
#### Can be reproduced ?
Yes
#### Steps:
Start a cluster with more than one node.

#### Expected behavior:
start successfully.

#### Actual behavior:
all nodes crashed.

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by zhangxu19830126** [comment]
duplicate with #187
