### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixcube#250]
Targeting >60% coverage for the raftstore package with the goal to further improve to >80% in near future.

**Comment by lni** [comment]
previous discussion in #169

**Comment by lni** [comment]
First batch for myself - 

raftstore/replica_*.go
storage/*

**Comment by zhangxu19830126** [comment]
batch for myself:

raftstore/all exclude replica_*.go

**Comment by lni** [comment]
raftstore now has a test coverage of 80%+

closed for now.
