### ISSUE TITLE
"Dispath to nil store" error appears when starting cube

### ISSUE THREAD

**Issue by LeftHandCold** [matrixorigin/matrixcube#379]
#### Can be reproduced ?
yes

#### Steps:
Make sure the "tick-interval" configuration item is equal to 1s
Start up cube

#### Expected behavior:
Normal start

#### Actual behavior:
Panic "dispath to nil store" occurs
![image](https://user-images.githubusercontent.com/14086886/140750166-7314fed3-ce72-48c9-b10d-910f544c0304.png)

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by lni** [comment]
MatrixCube had some delays on electing the new leader, this delay itself has been addressed in PR #380. However, please note that in Raft, there is no guarantee on how fast we can get a new leader elected. MatrixOne, including the cube_driver, should set its timeout value to be sufficiently large (e.g. 20x of the election timeout). Also note that even with such very large election timeout, in extreme situations, it is still possible to not having the new leader elected within that allowed time period.

**Comment by lni** [comment]
@LeftHandCold please have a look on the comments above.
