### ISSUE TITLE
Lock copying issue in raftstore.newReplica

### ISSUE THREAD

**Issue by reusee** [matrixorigin/matrixcube#425]
#### Can be reproduced ?
yes

#### Steps:
go vet ./...

#### Expected behavior:
no warning

#### Actual behavior:
raftstore/replica.go:132:22: literal copies lock value from *store.cfg: github.com/matrixorigin/matrixcube/config.Config contains github.com/matrixorigin/matrixcube/components/prophet/config.Config contains struct{sync.RWMutex; jobProcessors map[github.com/matrixorigin/matrixcube/components/prophet/pb/metapb.JobType]github.com/matrixorigin/matrixcube/components/prophet/config.JobProcessor}

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by zhangxu19830126** [comment]
Fix by #675
