### ISSUE TITLE
Potential nil pointer dereference in stateMachine.doExecConfigChange

### ISSUE THREAD

**Issue by reusee** [matrixorigin/matrixcube#427]
#### Can be reproduced ?
yes

#### Steps:
https://github.com/matrixorigin/matrixcube/blob/77729741a1ee16148ee5c0940d5f1cda16e978a3/raftstore/replica_state_machine_exec.go#L110

the `p` is nil at this line

#### Expected behavior:
no warning

#### Environment:
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

#### Additional context:
- Error message from client:
- Server log:
- Other information:

**Comment by zhangxu19830126** [comment]
Already fixed
