### ISSUE TITLE
Old membership changes can be applied on top of more recent membership status

### ISSUE THREAD

**Issue by lni** [matrixorigin/matrixcube#79]
Consider the following case - 

cube applies entries up to index 100, let's say it is a configuration change entry. the latest membership info is persistently stored on disk. 
we also assume that the previous configuration change is at entry index 80. 
after reboot, cube is told that the segment ID is 50, so it restores the latest saved membership info (at index 100) and rolls back to entry with index 51 and starts applying entries from index 51. when applying entry at index 80 again, it will be applied on top of the latest applied membership state which is at index 100.

**Comment by lni** [comment]
The fundamental issue here is that we have a hybrid RSM - a mix of in memory and on disk RSM. 

A potential fix is to only apply configuration changes that are more recent than the one currently in use.

**Comment by zhangxu19830126** [comment]
Fix at  #102
