### ISSUE TITLE
restart failed

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixcube#80]
Problem: failed to restart an existed cube cluster. parts of error logs are as follows:
![image](https://user-images.githubusercontent.com/77312370/128489949-24ae80ac-3f59-4602-8e9e-2ed9c19f6d77.png)

refer to https://github.com/matrixorigin/matrixcube/blob/master/components/prophet/schedule/placement/rule_manager.go#L123

**Comment by zhangxu19830126** [comment]
duplicate with #81
